---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - configuration.konghq.com.konghq.com
  resources:
  - kongplugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.konghq.com.konghq.com
  resources:
  - kongplugins/finalizers
  verbs:
  - update
- apiGroups:
  - configuration.konghq.com.konghq.com
  resources:
  - kongplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io.konghq.com
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io.konghq.com
  resources:
  - ingresses/finalizers
  verbs:
  - update
- apiGroups:
  - networking.k8s.io.konghq.com
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
